source "http://rubygems.org"

gem "rails", "3.1.3"
gem "haml-rails"
gem "jquery-rails"
gem "sass"
gem "coffee-script"
gem "pg"
gem "simple_form"
gem "twitter-bootstrap-rails"

group :development, :test do
  gem "rspec-rails", "2.7"
  gem "database_cleaner"
  gem "fabrication"
  gem "capybara", ">= 1.1.2"
  gem "spork"
  gem "shoulda-matchers"
end
