source "http://rubygems.org"

gem "rails", "3.1.3"
gem "haml-rails"
gem "jquery-rails"
gem "pg"
gem "sass"
gem "coffee-script"
gem "simple_form"
gem "jquery-ui-bootstrap-rails"

group :development, :test do
  gem "rspec", "2.7"
  gem "rspec-rails", "2.7"
  gem "rspec-core", "2.7"
  gem "rspec-expectations", "2.7"
  gem "rspec-mocks", "2.7"
  gem "database_cleaner"
  gem "fabrication"
  gem "capybara", ">= 1.1.2"
  gem "spork"
end
