source "http://rubygems.org"

gem "rails", "3.1"
gem "pg"
gem "haml-rails"
gem "simple_form"
gem "jquery-rails"

group :test do
  gem "rspec", "~> 2.7"
  gem "rspec-rails", "~> 2.7"
  gem "rspec-core", "~> 2.7"
  gem "rspec-expectations", "~> 2.7"
  gem "rspec-mocks", "~> 2.7"
  gem "database_cleaner", "~> 0.6"
  gem "spork", "~> 0.9.0.rc"
  gem "fabrication", "~> 1.0"
end

