#!/usr/bin/env ruby

puts "Loading script/rails"

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)

puts "Loading rails/commands"
require 'rails/commands'
